### ISSUE TITLE
Compliation / Upload issues 

### ISSUE THREAD

**Issue by lastebil** [TEAMarg/DM-09-demoScene#1]
It seems this code will not link currently - it throws errors during the linking stage:

    `osc' referenced in section `.text' of /tmp/user/1000/ccgtLXcF.ltrans0.ltrans.o: defined in discarded section `.text' of /tmp/arduino_build_109948/sketch/ATMlib.cpp.o (symbol from plugin)

This is very possibly issue with Arduino's latest toolchain, some googling led me to the conclusion something changed with the linker with some other projects...

I can provide full output of the compiler's errors if need be, but the relevant linking issue (repeated several times in the full error output with difference reference points) is above.

I did not find a method of fixing this referenced to the other projects that suffered linking errors, except to use an earlier version of the Arduino IDE.  I imagine that's not the best solution (:

My _guess_ is that the linker is not initializing the same way it did before, but as I'm not familiar with the linking process used.

(and yes, I very, very much want to see this demo (:  )

**Comment by JO3RI** [comment]
Yep, troubles with the new Arduino IDE.

We'll fix it some day, but for now, If you want to see it very very much, you beter just download IDE 1.6.9

We'll also provide HEX files soon, no more need for compiling stuff, just uploading will do.

**Comment by lastebil** [comment]
I'll do that...

any idea if the non-gui method works (i.e. http://playground.arduino.cc/Learning/CommandLine ? )  If not, well, I'll try that anyway (:

Also, any chance you'd be doing one of these demos for Revision?  (Demoparty, Germany, Easter.)  (Or even Outline, which is slightly closer to you in the Netherlands.)  (I am planning to make one myself.)

**Comment by JO3RI** [comment]
Actually I'm from Belgium :)

Command line will not help.

Anyway we are working on a new tracker player with a much smaller song footprint and doesn't have the problem this one has.

Yes I would love doing a demoparty someday, but I still think I'm not good enough ...

**Comment by lastebil** [comment]
Belgium: Yes, that's why I asked (:  Lots of Belgians go to Revision.  In fact, if they didn't go, there would need to be a new head of jury and new network team (:

You're good enough.  Trust me.  We'd love to see all of you there.  Or Evoke, or Outline.

Tracker player: awesome.  Well, I'll get to work on my demo (:

**Comment by lastebil** [comment]
I actually solved the issue by using platformio and the deviot plugin for sublime text.  (I possibly could have done it fully from the command line, but ... this is more comfortable for me (:

It threw some warnings, but it compiled and uploaded fine.

Issue solved (:

**Comment by JO3RI** [comment]
added a .arduboy file with all 3 chiptunes, you'll need an Arduboy Game Loader to upload this file
